R08 - [Lojista] Cadastrar Empresa e R09 - [Lojista] Gerenciar Empresa
disciplinas-prof-Edeilson-UFT/proj-sist-2021-2 pull request #12
Opened 2021-10-22 01:23 UTC by thaisclxt

## Observações Gerais:
- Os dois requisitos estão no mesmo Pull Request, pois ambos estão na mesma branch `develop` e enquanto implementávamos o R09, o R08 ainda estava em revisão. Pedimos desculpas pela bagunça, não ocorrerá novamente.

## R08 - [Lojista] Cadastrar Empresa 
- [Cartão do Trello](https://trello.com/c/aGxyVeIj/5-r08-lojista-cadastrar-empresa)
- Grupo responsável pelo R08 - [Lojista] Cadastrar Empresa:
  - Grupo 1 
- Grupo responsável pela revisão:
  - Grupo 2
- [22:22 - 21/10/21] Release pronta para a revisão.

### Observações:
- Para acessar a página de cadastrar empresas, basta clicar em __Cadastre seu Restaurante ou Mercado__ no footeBar da HomePage.

## R09 - [Lojista] Gerenciar Empresa
- [Cartão do Trello](https://trello.com/c/co5fEf1k/25-r09-lojista-gerenciar-empresa)
- Grupo responsável pelo R09 - [Lojista] Gerenciar Empresa:
  - Grupo 1 
- Grupo responsável pela revisão:
  - Grupo 2
- [22:09 - 25/10/21] Release pronta para a revisão. 

### Observações:
- Como não existe método de log-in do lojista, algumas medidas de contorno foram tomadas:
  - O botão "Ifood empresas" na footer bar agora redireciona à pagina home do restaurante. Esta implementação é temporária e aguarda um método definitivo de acesso.
  - Ao clicar em 'Editar perfil' é pssível visualizar uma tela que será melhor implementada no próximo requisito. Neste requisito, foi implementado o backend do upload da imagem de perfil, com uma área drag and drop para o envio de imagens nos formatos jpg e png. É possível encontrar as imagens em storage -> uploads console do firebase.

2021-10-31 14:37 UTC, mdmundo commented on lib/app/modules/home/home_module.dart
> +    ModuleRoute(RestaurantRegisterModule.routeName,
c329043da7f8a9f3856cb01b667aeef40236ee3a

2021-10-31 14:37 UTC, mdmundo commented on lib/app/modules/register/restaurant/components/page_two/register_card.dart
> +  final RegisterStore registerStore;
c329043da7f8a9f3856cb01b667aeef40236ee3a

2021-10-31 15:46 UTC, mdmundo commented
> OBS:
> 
> * A estrutura de arquivos continua a mesma;
> * Alguns arquivos não tem os mesmos nomes que suas respectivas classes;
> 
> Após a aula detalho melhor algumas coisas.

e1f33faf62b17fad161d4a4907391d27781046cd

2021-11-01 23:14 UTC, thaisclxt commented
Observações com novo meio de acesso ao requisito R09 foram adicionadas na descrição deste Pull Request.

2021-11-03 19:55 UTC, djesusguimaraes commented on lib/app/app_module.dart
> +    ModuleRoute(RestaurantHomeModule.routeName, module: RestaurantHomeModule()),
Declaração de módulo duplicada para `RestaurantHomeModule`

2021-11-03 20:05 UTC, djesusguimaraes commented on lib/app/global/widgets/footer_bar/custom_footer.dart
> +  final List<String> navigator = ['register/restaurant/page1', '', '', 'restaurant_home'];
Entendo a motivação da lista, mas é mais seguro e manutenível declarar as rotas com referência à classe.

* Ex:
  * `'register/restaurant/page1'` poderia ser substituido pela concatenação `RestaurantRegisterModule.routeName + RestaurantRegisterPage.routeName`

Dessa forma facilitamos a mudança ou manutenção das rotas.

2021-11-03 21:07 UTC, djesusguimaraes commented on lib/app/modules/restaurant_register/restaurant_register_module.dart
> +  List<ModularRoute> get routes => [
* Os nomes de diretório foram redefinidos para `register_owner` e `register_shop`, mas as rotas seguem com a nomenclatura antiga. E declaradas de forma estática, o que exige a repetição em outros arquivos, como nos arquivos `register_card.dart`. Abaixo uma observação sobre esses arquivos.


* Nesse mesmo sentido há uma repetição de classes e arquivos para `register_card.dart` (com classe nomeada `RegisterCard`) em `pages/register_owner` e `pages/register_shop`. As classes não tem o mesmo conteúdo. A mesma situação se aplica aos arquivos `register_formulary.dart`, como observado na imagem abaixo:

  ![image](https://user-images.githubusercontent.com/66970708/140192442-3dc22a67-28ac-4e1c-9e50-44b9950b5ac8.png)

2021-11-03 21:08 UTC, djesusguimaraes commented on lib/app/modules/restaurant_register/pages/register_shop/register_card.dart
> +                          dispose();
Não há a necessidade de chamar manualmente o método `dispose()`, ao sair da página ele será chamado automaticamente.

2021-11-03 21:13 UTC, djesusguimaraes commented on lib/app/modules/restaurant_register/pages/register_shop/register_card.dart
> +      Modular.to.navigate('page1');
* Instanciar uma variável, ou um getter na classe de destino, como no exemplo abaixo(linha 13), elimina a necessidade de repetição manual da rota.

  ![image](https://user-images.githubusercontent.com/66970708/140193502-d0e7e2a4-8f72-4552-b74f-c994463770e3.png)

2021-11-03 21:31 UTC, djesusguimaraes commented on lib/app/modules/restaurant_register/restaurant_register_store.dart
> +    restaurant.add({
* Não é responsabilidade do `store.dart` fazer comunicação com o database, enviar ou receber dados diretamente, para isso usamos a camada `Repository`, como aplicado pelo Grupo 3 no Card R03. Exemplo abaixo:

  ![image](https://user-images.githubusercontent.com/66970708/140195669-f2a000a5-2ec7-42c9-9c93-192a4345e780.png)

2021-11-03 21:33 UTC, djesusguimaraes commented on lib/app/modules/restaurant_home/restaurant_home_store.dart
> +      await FirebaseStorage.instance.ref('uploads/${e.name}').putBlob(e);
* Não é responsabilidade do `store.dart` fazer comunicação com o database, enviar ou receber dados diretamente, para isso usamos a camada `Repository`, como aplicado pelo Grupo 3 no Card R03. Exemplo abaixo:

  ![image](https://user-images.githubusercontent.com/66970708/140195669-f2a000a5-2ec7-42c9-9c93-192a4345e780.png)

2021-11-03 21:44 UTC, djesusguimaraes requested changes
### Parecer
#### [Card R09](https://trello.com/c/co5fEf1k/25-r09-lojista-gerenciar-empresa)
* Dados os devidos ajustes, já observados acima, considero o card, majoritariamente Front-End, como APROVADO COM OBSERVAÇÕES.

#### [Card R08](https://trello.com/c/aGxyVeIj/5-r08-lojista-cadastrar-empresa)
* As observações anteriores sobre a usabilidade parecem ter sido bem corrigidas, portanto ficam apenas os comentários em código para resolução. 
* Dadas as observações anteriores, considero o PR, como um todo, como REPROVADO. Já que há comentários remanescentes das outras revisões, ainda não resolvidos.

2021-11-04 00:27 UTC, Ericboo commented on lib/app/modules/restaurant_home/restaurant_home_store.dart
> +      await FirebaseStorage.instance.ref('uploads/${e.name}').putBlob(e);
Este erro será corrigido na implementação do requisito R12. Esta decisão foi tomada pelo grupo 1 adjunto ao grupo 2 pelos seguintes motivos:

- O requisito R12 já está em desenvolvimento e já implementou esse arquivo.
- O requisito R9, ao qual esse erro atende, já foi aprovado.

2021-11-07 04:00 UTC, djesusguimaraes approved these changes
### Conclusão

- Visto que as alterações foram atendidas e o trabalho está organizado e funcional. Considero o [Card R08](https://trello.com/c/aGxyVeIj/5-r08-lojista-cadastrar-empresa) APROVADO.

2021-11-07 04:00 UTC, merged