R04 - [Cliente] Cadastrar Cliente
disciplinas-prof-Edeilson-UFT/proj-sist-2021-2 pull request #14
Opened 2021-11-01 00:10 UTC by djesusguimaraes

### Detalhes
* [Card no Trello](https://trello.com/c/OLJ9Soyc/1-r04-cliente-cadastrar-cliente)
* Registro de Cliente
  * Apenas clientes com telefone válido
  * O acesso à página é feito pelo botão `Ainda não tenho conta` na tela de login, ou adicionando um e-mail não existente no FirebaseAuth

#### Relatório de implementação
* A pasta `modules/register_client` foi onde implementamos a atividade;
* Uma implementação paralela foi a detecção de e-mail inexistente e redirecionamento para `RegisterClientModule` em `AuthModule`
* **Dados para teste (telefone para verificação)**
  * Número: `+55 7444 555666`
  * Código de Verificação: `123456`

2021-11-02 00:46 UTC, FilipeMSouza commented on lib/app/modules/register_client/pages/confirm_phone/confirm_phone_page.dart
> +          margin: const EdgeInsets.symmetric(horizontal: 100.0, vertical: 10.0),
Colocar um virgula após o "vertical: 10.0" para melhor leitura

2021-11-02 00:47 UTC, FilipeMSouza commented on lib/app/modules/register_client/pages/confirm_phone/confirm_phone_page.dart
> +          margin: const EdgeInsets.symmetric(horizontal: 100.0, vertical: 10.0),
Colocar um virgula após o "vertical: 10.0" para melhor leitura

2021-11-02 00:49 UTC, FilipeMSouza commented on lib/app/global/widgets/app_bar/components/components_app_bar.dart
> +class RegisterButton extends StatelessWidget {
Pode ser burrice mas não encontrei esse simbolo sendo utilizao visualmente dentro da aplicação

2021-11-02 00:54 UTC, FilipeMSouza commented on lib/app/modules/auth/auth_page.dart
> +                                'Ainda não tenho conta',
Esse botão tem um hover que não segue os padrões da aplicação, por favor remover ele ou tornar ele transparente

2021-11-02 00:56 UTC, FilipeMSouza commented on lib/app/modules/register_client/pages/confirm_phone/confirm_phone_page.dart
> +                              child: TextButton(
Esse botão tem um hover que não segue os padrões da aplicação, por favor remover ele ou tornar ele transparente

2021-11-02 00:57 UTC, FilipeMSouza commented on lib/app/modules/register_client/pages/register_client_page/register_client_page.dart
> +                              child: TextButton(
Esse botão tem um hover que não segue os padrões da aplicação, por favor remover ele ou tornar ele transparente

2021-11-02 00:58 UTC, FilipeMSouza commented on lib/app/modules/register_client/pages/register_client_page/register_client_page.dart
> +                        Wrap(
Esses dois elemento não se alinham entre si, o texto esta mais alto do que o checkbox

2021-11-02 01:01 UTC, FilipeMSouza commented on lib/app/modules/register_client/pages/register_client_page/register_client_page.dart
> +                        CustomSubmit(
Quando você aperta o botão ele corre uma especie de hover branco sobre o botão, isso se possivel pode ser alterado para um tom mais claro de vermelho

2021-11-02 01:05 UTC, FilipeMSouza commented on lib/app/modules/register_client/register_client_store.dart
> +import 'dart:html';
Biblioteca não utilizada, favor remover

2021-11-02 01:10 UTC, FilipeMSouza commented on lib/app/modules/register_client/register_client_store.dart
> +  Future<void> verifyCode() async {
Quando vc entra com um codigo que não é o correto aparece o segunite erro 
![image](https://user-images.githubusercontent.com/33045754/139770703-b9cdbbcd-43ed-4aa6-aeaf-ccad772d1dac.png)

2021-11-02 01:27 UTC, FilipeMSouza requested changes
- O arquivo register_cliente_store.dart tem um problema com a importação da biblioteca dart:html, que não está sendo usada

![image](https://user-images.githubusercontent.com/33045754/139771711-e16b4c4f-bf84-4bdd-bb11-a1ab62e15ed4.png)


- O TextButton que redireciona para o cadastro tem um hover fora do padrão, normalmente esse  botão no ifood não tem isso, então se formos seguir esse padrão não tem necessidade desse hover 

![image](https://user-images.githubusercontent.com/33045754/139771789-f090e49c-4840-49cc-9ba5-3c3b9d8e8c95.png)


- No cadastro o alinhamento da checkbox e do texto "declaro que li e aceito os termos de uso" não coincidem, o texto está um pouco mais alto do que a checkbox,

- Também sobre checkbox o preenchimento de cor dela deve seguir as cores padrões do projeto, sendo assim necessário trocar a cor de preenchimento para cor secundaria do schemes.dart

![image](https://user-images.githubusercontent.com/33045754/139771809-ddd5e9d7-14c4-4d5f-a39c-d1530bbb2c74.png)

- Realizamos um cadastro com um email que já tinha sido usado e ele deu continuidade com o cadastro e prossegui com a confirmação de telefone, Creio que isso não deveria ser possivel e no campo de digitação do email ele deveria acusar que o email já foi usado

- Quando você tenta confirmar enviar o registro sem ter preenchido a checkbox não existe nada indicando que ela precisa estar preenchida

- Ao colocar um código de confirmação que não e valido a aplicação crasha e aparecendo um erro de flutter e redireciona para a pagina inicial e o usuário e cadastrado no banco.

- quando realizamos um login com uma conta que já existe ele nos redireciona para uma tela que fala de confirmação de email, e quando clicamos no logo do site ele redireciona pra /auth, quando tentamos sair caso o email não tenha sido verificado o login é executado entretanto ele não executa a função de logout, ficando preso no usuário 

- Existe uma diferença de cores na appbar considerando as mudanças que vcs fizeram no card anterior, creio eu que o uso do schema.dart que carrega os padrões de cores da aplicação devam ser aplicados 

## Conclusão
- Devido aos comentarios e mudanças requisitadas a PR foi recusada

2021-11-02 01:27 UTC, FilipeMSouza commented on lib/app/modules/register_client/widgets/custom_submit_button.dart
> +  TextStyle get digitedText => GoogleFonts.getFont('Sen', fontSize: 22.0);
Essa fonte nao deveria seguir os padrões do projeto usando Nunito?

2021-11-02 01:27 UTC, FilipeMSouza commented on lib/app/modules/auth/auth_page.dart
> +                TextButton(
Ambos os botões possuem um hover que não segue os padrões da aplicação, por favor remover ele ou tornar ele transparente

2021-11-02 01:27 UTC, FilipeMSouza commented on lib/app/modules/auth/auth_store.dart
> +      if (e.toString() == 'Exception: O e-mail não foi encontrado') {
Ao tentar logar mesmo colocando um email inxistente não vi essa mensagem

2021-11-02 01:27 UTC, FilipeMSouza commented on lib/app/modules/register_client/widgets/custom_text_field.dart
> +      GoogleFonts.getFont('Sen', fontSize: 16.0, fontWeight: FontWeight.bold);
Essa fonte nao deveria seguir os padrões do projeto usando Nunito?

2021-11-06 19:54 UTC, djesusguimaraes commented on lib/app/global/widgets/app_bar/components/components_app_bar.dart
> +class RegisterButton extends StatelessWidget {
Pronto

2021-11-06 20:18 UTC, djesusguimaraes commented on lib/app/modules/register_client/pages/confirm_phone/confirm_phone_page.dart
> +          margin: const EdgeInsets.symmetric(horizontal: 100.0, vertical: 10.0),
Pronto

2021-11-06 20:19 UTC, djesusguimaraes commented on lib/app/modules/register_client/pages/confirm_phone/confirm_phone_page.dart
> +          margin: const EdgeInsets.symmetric(horizontal: 100.0, vertical: 10.0),
Pronto

2021-11-06 20:33 UTC, djesusguimaraes commented on lib/app/modules/auth/auth_page.dart
> +                                'Ainda não tenho conta',
Pronto

2021-11-06 22:03 UTC, djesusguimaraes commented on lib/app/modules/auth/auth_page.dart
> +                TextButton(
Pronto

2021-11-06 22:05 UTC, djesusguimaraes commented on lib/app/modules/auth/auth_store.dart
> +      if (e.toString() == 'Exception: O e-mail não foi encontrado') {
A mensagem de email inexistente é apresentada ao usuário por meio do pop-up oferecendo a criação de conta, ou uma nova tentativa para corrigir o e-mail.
![image](https://user-images.githubusercontent.com/66970708/140625085-f24d70e4-40d7-402a-a95f-8988f8cf662f.png)

2021-11-06 22:07 UTC, djesusguimaraes commented on lib/app/modules/register_client/pages/confirm_phone/confirm_phone_page.dart
> +                              child: TextButton(
Pronto

2021-11-06 23:32 UTC, djesusguimaraes commented on lib/app/modules/register_client/pages/register_client_page/register_client_page.dart
> +                        Wrap(
Pronto

2021-11-06 23:32 UTC, djesusguimaraes commented on lib/app/modules/register_client/pages/register_client_page/register_client_page.dart
> +                        CustomSubmit(
Pronto

2021-11-06 23:38 UTC, djesusguimaraes commented on lib/app/modules/register_client/pages/register_client_page/register_client_page.dart
> +                              child: TextButton(
Pronto

2021-11-07 00:14 UTC, djesusguimaraes commented on lib/app/modules/register_client/widgets/custom_submit_button.dart
> +  TextStyle get digitedText => GoogleFonts.getFont('Sen', fontSize: 22.0);
Pronto

2021-11-07 00:14 UTC, djesusguimaraes commented on lib/app/modules/register_client/widgets/custom_text_field.dart
> +      GoogleFonts.getFont('Sen', fontSize: 16.0, fontWeight: FontWeight.bold);
Pronto

2021-11-07 00:15 UTC, djesusguimaraes commented on lib/app/modules/register_client/register_client_store.dart
> +import 'dart:html';
Pronto

2021-11-07 01:05 UTC, djesusguimaraes commented on lib/app/modules/register_client/register_client_store.dart
> +  Future<void> verifyCode() async {
Apenas variáveis erradas. Pronto.

2021-11-07 02:37 UTC, djesusguimaraes commented
#### Modificações Atendidas
- Adicionada verificação de unicidade para:
  - E-mail
  - CPF
  - Telefone
  - OBS: Essa verificação depende de uma limpeza no banco, pois a verificação da tabela `clients` precisa de dois atributos, são eles: `phone` e `cpf`, mas nem todos os registros tem o atributo `phone`.

2021-11-08 13:32 UTC, FilipeMSouza commented
Quando clicamos em enviar cadastro sem ter a checkbox de termos de uso nao aparece nenhuma mensagen indicando onde esta o erro

2021-11-08 13:39 UTC, FilipeMSouza commented on lib/app/modules/register_client/pages/confirm_phone/confirm_phone_page.dart
> +                          label: 'Enviar',
quano eu inseri o codigo e apertei o botão nada aconteceu

2021-11-08 14:12 UTC, FilipeMSouza reviewed
Correções pontuais a serem feitas, por isso a PR foi negada

2021-11-08 14:12 UTC, FilipeMSouza commented on lib/app/modules/register_client/pages/register_client_page/register_client_page.dart
> +                                "Declaro que li e aceito os termos de uso",
- Se enviamos o registo sem marcar esse campo ele nao indica nenhum erro, mesmo sendo óbvio que esse campo é necessario seria muito bom um alerta que um alerta fosse colocado na tela

2021-11-08 14:12 UTC, FilipeMSouza commented on lib/app/modules/register_client/widgets/custom_submit_button.dart
> +      GoogleFonts.getFont('Roboto', fontSize: 22.0, color: Colors.white);
- Eu tinha comentado na ultima revisão em questao das fontes , foi estabelecido pelo grupo 1 e dps acordado com todos o uso do fonte nunito, e usar uma fonte diferente do padrão da uma pegada

2021-11-08 14:12 UTC, FilipeMSouza commented on lib/app/global/widgets/app_bar/components/user_profile_options.dart
> +        Modular.to.navigate(AuthModule.routeName);
- Isso aq nao deveria ir pra pagina home?

2021-11-11 19:26 UTC, djesusguimaraes commented on lib/app/global/widgets/app_bar/components/user_profile_options.dart
> +        Modular.to.navigate(AuthModule.routeName);
Resolvido

2021-11-11 19:27 UTC, djesusguimaraes commented on lib/app/modules/register_client/widgets/custom_submit_button.dart
> +      GoogleFonts.getFont('Roboto', fontSize: 22.0, color: Colors.white);
Resolvido

2021-11-11 19:28 UTC, djesusguimaraes commented on lib/app/modules/register_client/pages/register_client_page/register_client_page.dart
> +                            hint: 'Insira seu email',
Esquecemos de trocar a mensagem de retorno, que antes tratava apenas do e-mail. Agora ela fala dos dados em geral.
![image](https://user-images.githubusercontent.com/66970708/141357191-5fea60dd-a7e8-4e42-93f2-e3ba0864925e.png)

2021-11-11 19:31 UTC, djesusguimaraes commented on lib/app/modules/register_client/pages/register_client_page/register_client_page.dart
> +                                "Declaro que li e aceito os termos de uso",
Resolvido

2021-11-11 19:48 UTC, djesusguimaraes commented
#### Observações
* Favor desconsiderar os arquivos do módulo `update_client_data`, que faz parte de outro requisito.
* Correções aplicadas, validações adicionadas e fonte corrigida.

2021-11-12 01:15 UTC, FilipeMSouza commented on lib/app/modules/register_client/register_client_store.dart
> +  Future<void> checkData() async {
- Não dispara notificação de erro caso use o comando alt+tab

2021-11-12 01:17 UTC, FilipeMSouza reviewed
PR negada por erro das validações no arquivo register_client_store.dart

2021-11-12 01:28 UTC, FilipeMSouza approved these changes
PR Aprovada

2021-11-12 01:29 UTC, merged