[R06 e R07] Acompanhamento e Avaliação do Pedido
disciplinas-prof-Edeilson-UFT/proj-sist-2021-2 pull request #15
Opened 2021-11-10 17:22 UTC by FilipeMSouza

## link para os cards
  - [Card R06](https://trello.com/c/yzPHJqkR/12-r06-cliente-acompanhar-pedido)
  - [Card R07](https://trello.com/c/CzjWR345/11-r07-cliente-avaliar-pedido)

# Acompanhar pedido
  - Esse card foi dividido em duas paginas, a primairia onde mostra o pedido em processo junto com os restaurantes mais pedidos e o historico
    - Como faltam algumas coisas de informações na tabela de cliente não tivemos como fazer o historico
    - Os mais pedido usamos a mesma função da pagina home que foi desenvolvida pelo grupo 1
  - O card de acompanhamento carrega o botão de cancelamento (nao esta sendo enviado ao banco pelos mesmo probelmas pois isso é algo que tem relação com historico e com cliente)
  - Ess card tambem tem o botão 'Acompanhamento' que redireciona para a pagina onde vai ter o status do pedido
### Pagina de Status do pedido
  - Um display com o nome da loja e um botão para um dialog  que recebe os dados do banco(Como tivemos um problema com o banco caso a pagina seja atualizada ele perde os valores, **isso mais uma vez tem relação com o firebase e o fato de precisarmos atualizar isso constantemente**)
  - O display de progresso tambem depende do banco para ser atualizado e do logista, com isso deixamos uma função que vai ser a responsavel por receber e mostar esse progresso encaminhada

# Avaliação de pedido
  - Esse é o nosso mais completo envia para o banco de dados e redireciona para a pagina de pedidos, ele não remove os pedidos a lista pois são estaticos devido aos problemas que nós citamos anteriormente
  - Ele se encontra na pasta rating order

2021-11-12 14:58 UTC, Ericboo commented
Olá, estou revisando especificamente o conteúdo pertencente ao mobx. 

Considero a aplicação do mobx em seu estado atual **APROVADA COM COMENTÁRIOS**, ou seja, apesar do que foi citado nos comentários, o código está organizado e funcional e, portanto, qualificado para aprovação.

> Esta decisão é valida apenas ao que diz respeito ao **mobx**. Aguardem a decisão final envolvendo os outros membros do grupo.

2021-11-12 16:54 UTC, nathans4ntos requested changes
Comentários dentro do código. Review referente ao 3.2 Verificar se os nomes de arquivo e classe condizem com o que nele há.

2021-11-12 21:03 UTC, thaisclxt requested changes
Oiee, estou revisando especificamente a parte visual dos requisitos.

Considero a aplicação em seu estado atual **REPROVADA** e solicito que os seguintes problemas sejam corrigidos:

### R06 - [Cliente] Acompanhar Pedido
- O pedido permanece no carrinho quando está na tela de _Meus Pedidos_. Estes deveriam sair do carrinho ao clicar em _pagar_ na tela de finalização do pedido.

- Corrigir o overflow:
![image](https://user-images.githubusercontent.com/62521620/141525413-2a752fac-96bd-4a1f-8926-29416d4f76b0.png)

- Ao cancelar o pedido, o usuário deveria ser direcionado para a tela inicial, além da mensagem já implementada avisando que o pedido foi cancelado. 
Da maneira como está agora, o usuário pode acompanhar o pedido mesmo tendo cancelado e cancelar de novo se ele quiser.

**Pagina de Status do pedido**
- No Ifood, onde estamos nos baseando para este projeto, a loja precisa confirmar o pedido e só assim o pedido fica pronto para ir para a entrega. Acredito que deveria mostrar a confirmação da loja antes de ir para a tela _Meus Pedidos_, ou alguma mensagem de que o pedido foi confirmado pela loja e está sendo preparado
![image](https://user-images.githubusercontent.com/62521620/141531339-e3435dea-ff73-4c99-b9c8-ed450043f5a4.png)
> Caso isso se enquandre em _Status_ - display de progresso, que depende do banco de dados para ser atualizado, nos avise e considere este comentário para quando o banco de dados estiver pronto para uso.



### R07 - [Cliente] Avaliar Pedido
- Adicione a cor _SecondaryColor_ ao cursor, no campo _Escreva uma avaliação_.
![image](https://user-images.githubusercontent.com/62521620/141533752-370cf462-1ada-46d3-9396-4d07da0da72f.png)


- Coloque R$ antes do valor do cupom, ao invés de depois. Além disso, o cupom de 0,99 não estava no carrinho e não está sendo calculado no valor total.
![image](https://user-images.githubusercontent.com/62521620/141533448-594845fa-6666-45fd-87cc-e3bfce7aea00.png)

2021-11-13 13:32 UTC, milenacrios requested changes
Alguns trechos, não são necessários, verificar e corrigir antes da aprovação

2021-11-13 13:32 UTC, milenacrios commented on lib/app/global/widgets/footer_bar/components/desktop_footer_bar.dart
> -import 'package:flutter/cupertino.dart';
Utilizar o cupertino é realmente necessário? Nesse caso, teríamos que está usando durante todo o projeto e como os imports do cupertino estão só no app_bar, não faz sentido utilizar.

2021-11-13 13:32 UTC, milenacrios commented on lib/app/global/widgets/footer_bar/components/mobile_footer_bar.dart
> -import 'package:flutter/cupertino.dart';
Utilizar o cupertino é realmente necessário? Nesse caso, teríamos que está usando durante todo o projeto e como os imports do cupertino estão só no app_bar, não faz sentido utilizar.

2021-11-13 13:32 UTC, milenacrios commented on lib/app/global/widgets/footer_bar/components/tablet_footer_bar.dart
> -import 'package:flutter/cupertino.dart';
Utilizar o cupertino é realmente necessário? Nesse caso, teríamos que está usando durante todo o projeto e como os imports do cupertino estão só no app_bar, não faz sentido utilizar.

2021-11-13 13:32 UTC, milenacrios commented on lib/app/modules/cart/components/drawer/pre_drawer_selector.dart
> -            largura: 250,
Alterar as variáveis para inglês como está sendo seguido no projeto.

2021-11-13 13:32 UTC, milenacrios commented on lib/app/modules/cart/components/payment/components/order_container.dart
>            const Divider(thickness: 1, color: Colors.black38),
Utilizar as cores previamente definidas em schemas.dart. Se não tiver esssa cor, adicioná-la como constante.

2021-11-13 13:32 UTC, milenacrios commented on lib/app/modules/cart/components/payment/pages/payment_page.dart
>            var largura = constraints.maxWidth;
Utilizar as variáveis em inglês como está sendo seguido no projeto.

2021-11-13 15:11 UTC, alineralncs commented
Estou revisando as regras de negócios que foram (ou não) implementadas nos requisitos.
# R06
De acordo com o card feito no trello, o R06 precisa ter essas 4 funcionalidades.
- Status de Pedido
- Reportar Danos
- Solicitar Troca
- Cancelar Pedido

A funcionalidade status de pedido não está ok, visto que não há nada indicando o status do pedido. 

![image](https://user-images.githubusercontent.com/38014924/141647740-e5d81281-f60b-454e-8d51-9ff66e976a2c.png)

A funcionalidade cancelar pedido não está ok, pois ao cancelar o pedido seria necessário sair da página também tendo em vista que da forma que está o pedido pode ser cancelado várias vezes.

![image](https://user-images.githubusercontent.com/38014924/141647684-d8012ed2-c6c0-4f16-a149-359339e7a8af.png)

Além disso, quando aperto nesse botão sair fico imposssibilitada de fazer qualquer outra coisa no sistema. 

![image](https://user-images.githubusercontent.com/38014924/141647885-ff739392-6112-4001-afb5-a4319235f411.png)

Não econtrei na página as funcionalidades: reportar danos e solicitar troca. 

![image](https://user-images.githubusercontent.com/38014924/141648032-b5ad46f9-3abf-4078-ae56-dd9fcf4a2c4b.png)


# R07
De acordo com o card feito no trello, o R07 precisa ter essas 2 funcionalidades.
- Avalição por estrelas (podendo avaliar de forma geral o pedido)
- Comentários

As duas funcionalidades estão ok. 
![image](https://user-images.githubusercontent.com/38014924/141648085-b1b42750-aa0e-4ebe-b132-56dc4fa02205.png)

De acordo com os pontos apresentados, peço que corrijam e terminam as funcionalidades. Portanto, a aplicação no seu estado atual **reprovada**.

2021-11-13 17:42 UTC, FilipeMSouza commented on lib/app/modules/order/components/rating/rating_prodct.dart
> +class RatingOrder extends StatelessWidget {
Resolvido

2021-11-13 17:49 UTC, FilipeMSouza commented on lib/app/modules/order/components/track/pages/desktop_oder_page.dart
>  class DesktopOrderPage extends StatefulWidget {
resolvido

2021-11-13 17:50 UTC, FilipeMSouza commented on lib/app/modules/order/components/track/pages/mobile_oder_page.dart
>  class MobileOrderPage extends StatefulWidget {
resolvido

2021-11-13 17:51 UTC, FilipeMSouza commented on lib/app/app_module.dart
> -    // ModuleRoute(OrderModule.routeName, module: OrderModule()),
nao sei pq estava comentado, mas nao era pra estar

2021-11-13 17:52 UTC, FilipeMSouza commented on lib/app/global/widgets/footer_bar/components/desktop_footer_bar.dart
> -import 'package:flutter/cupertino.dart';
![image](https://user-images.githubusercontent.com/33045754/141653996-f7350020-8bd0-45ba-9689-8e2a38b567fb.png)

2021-11-13 17:53 UTC, FilipeMSouza commented on lib/app/global/widgets/footer_bar/components/mobile_footer_bar.dart
> -import 'package:flutter/cupertino.dart';
![image](https://user-images.githubusercontent.com/33045754/141654017-7a20db84-e1d3-4aee-a858-c504727e2150.png)

2021-11-13 17:53 UTC, FilipeMSouza commented on lib/app/global/widgets/footer_bar/components/tablet_footer_bar.dart
> -import 'package:flutter/cupertino.dart';
![image](https://user-images.githubusercontent.com/33045754/141654028-ad2fb8f6-cc96-4ada-8a69-91e43e37eb18.png)

2021-11-13 18:00 UTC, FilipeMSouza commented on lib/app/modules/cart/components/payment/components/order_container.dart
>            const Divider(thickness: 1, color: Colors.black38),
Nova cor adiconada nos schemas

2021-11-13 18:00 UTC, FilipeMSouza commented on lib/app/modules/cart/components/payment/pages/payment_page.dart
>            var largura = constraints.maxWidth;
resolvido

2021-11-13 18:00 UTC, FilipeMSouza commented on lib/app/modules/cart/components/drawer/pre_drawer_selector.dart
> -            largura: 250,
resolvido

2021-11-14 10:58 UTC, mdmundo commented
O código foi bem escrito e acho que está pronto pro _merge_ no quesito otimizações. Peço desculpas pelo atraso.✋

2021-11-16 01:09 UTC, FilipeMSouza commented
Correções feitas no domingo dia 14/11/2021 às 17:03

2021-11-16 09:59 UTC, mdmundo approved these changes

2021-11-16 16:14 UTC, Ericboo approved these changes

2021-11-16 16:23 UTC, nathans4ntos approved these changes

2021-11-16 19:51 UTC, thaisclxt requested changes
Apenas uma solicitação de mudança não foi feita corretamente, as demais estão ok. Portanto, pull request **reprovado**, até que a alteração seja feita.

--------------------
Adicionei 3 produtos ao carrinho, concluí a compra e fui para a tela _Meus Pedidos_. Ao clicar no carrinho, estou vendo 1 pedido. Não deveria ver nenhum, já que concluí o pedido.
> Solicitei anteriormente que os pedidos saíssem do carrinho, porém eles permanecem e permaneceu apenas 1 como pode ver na imagem abaixo

![image](https://user-images.githubusercontent.com/62521620/142054602-12abeb69-dd76-4e1d-88da-7457d61b74d6.png)

2021-11-16 20:10 UTC, milenacrios approved these changes
Ainda não foi dada uma explicação sobre o import do cupertino no app_bar. Porém, considero aprovado o pull request.

2021-11-16 21:10 UTC, alineralncs commented
Considero a pull request *aprovada*

2021-11-16 21:10 UTC, thaisclxt approved these changes

2021-11-16 21:11 UTC, merged