Develop
disciplinas-prof-Edeilson-UFT/proj-sist-2021-2 pull request #19
Opened 2021-11-21 05:25 UTC by djesusguimaraes

### Detalhes
* [Card no Trello](https://trello.com/c/zy5okSBb/3-r10-cliente-alterar-dados-pessoais)
* Edição de Dados do Cliente:
  * Telefone e Nome;
  * Se editar o telefone o sistema segue para uma verificação por envio de código.

#### Relatório de implementação
* A pasta `modules/update_client_data` foi onde implementamos a atividade;
* Ela tem referência para o módulo `register_client` para reutilizar algumas funções e para `/global/repositories/client_address` onde realizamos o update no firebase.

#### Acesso na interface:
* Logando com um usuário cadastrado com e-mail e senha pelo próprio sistema:
  * Basta acessar as opções de usuário na appBar(mesmo caminho no ifood): 
![image](https://user-images.githubusercontent.com/66970708/142750612-6b798420-d9f8-49a3-b83f-7832072d53aa.png)

2021-11-21 15:20 UTC, Ericboo approved these changes
Olá, estou revisando especificamente a parte de implementação do Mobx do seu requisito.

A aplicação está adequada e, por isso, a considero **APROVADA**.

> Esta decisão diz respeito apenas à aplicação do mobx. Aguarde a decisão final tomada em conjunto com os outros membros do grupo.

2021-11-21 19:12 UTC, alineralncs approved these changes
Oie, estou revisando as regras de negócios que foram (ou não) implementadas nos requisitos.
Logo, considero aprovada a pull request.

2021-11-21 19:23 UTC, milenacrios reviewed
Há algumas observações que podem ser acatadas pelo grupo em relação ao uso de cores que já estão definidas e padronizadas no arquivo schemas.dart, tornando o uso de Colors.red, por exemplo, desnecessário, mas de maneira geral considero o pull request APROVADO.

2021-11-21 19:23 UTC, milenacrios commented on lib/app/global/widgets/app_bar/components/components_app_bar.dart
> -          color = Colors.red;
Colors.red desnecessária, usar cor definida em schemas.dart (secondary collor)

2021-11-21 19:23 UTC, milenacrios commented on lib/app/modules/update_client_data/pages/confirm_new_phone_page.dart
> +          backgroundColor: Colors.red,
Usar cor definida em schemas.dart

2021-11-21 19:23 UTC, milenacrios commented on lib/app/modules/update_client_data/pages/confirm_new_phone_page.dart
> +          backgroundColor: Colors.red,
Usar cor definida em schemas.dart

2021-11-21 21:26 UTC, djesusguimaraes commented on lib/app/global/widgets/app_bar/components/components_app_bar.dart
> -          color = Colors.red;
Resolvido.

2021-11-21 21:27 UTC, djesusguimaraes commented on lib/app/modules/update_client_data/pages/confirm_new_phone_page.dart
> +          backgroundColor: Colors.red,
Resolvido.

2021-11-21 21:27 UTC, djesusguimaraes commented on lib/app/modules/update_client_data/pages/confirm_new_phone_page.dart
> +          backgroundColor: Colors.red,
Resolvido.

2021-11-22 03:35 UTC, marcos1079 requested changes
- diminuir o tamanho da fonte do titulo 'editar dados'.
- alterar a cor onde estiverem chamando colors.red para secondaryColor.
- alterar a cor dos campos não editáveis 'E-mai' e 'CPF' para tertiaryColor.
- aumentar o card central de modo que fique no tamanho da tela. Como na imagem anexada no card do trello.

2021-11-22 16:54 UTC, djesusguimaraes commented
## Correções
Observações corrigidas @marcos1079

2021-11-22 18:11 UTC, mdmundo approved these changes

2021-11-23 10:28 UTC, nathans4ntos requested changes
Analisando apenas a parte de organização de arquivos e classes, só dois detalhes me chamaram atenção, portanto, assim que corrigido, pode considerar aprovado por mim.

2021-11-23 10:28 UTC, nathans4ntos commented on lib/app/modules/register_client/widgets/custom_submit_button.dart
>  class CustomSubmit extends StatefulWidget {
Em todos os outros locais, vocês utilizaram exatamente o nome do arquivo para a classe, favor, repetir neste caso

2021-11-23 10:43 UTC, nathans4ntos requested changes

2021-11-23 10:43 UTC, nathans4ntos commented on lib/app/modules/update_client_data/pages/update_client_data_page.dart
> +class UpdateClientDataPage extends StatefulWidget {
Este arquivo e classe estão com o nome igual ao de outro arquivo e classe na /update_client_data, creio eu que possa gerar uma certa confusão, não?

2021-11-23 10:45 UTC, djesusguimaraes commented on lib/app/modules/update_client_data/pages/update_client_data_page.dart
> +class UpdateClientDataPage extends StatefulWidget {
Resolvido.

2021-11-23 10:46 UTC, djesusguimaraes commented on lib/app/modules/register_client/widgets/custom_submit_button.dart
>  class CustomSubmit extends StatefulWidget {
Resolvido.

2021-11-23 10:48 UTC, nathans4ntos reviewed
Com todas as modificações solicitadas na parte de organização de arquivos e classes realizadas, considero o pr APROVADO no que tange a isto.

2021-11-23 10:51 UTC, nathans4ntos approved these changes
Como dito no comentário anterior, considero APROVADO na parte de organização de arquivos e classes.

2021-11-23 14:47 UTC, marcos1079 approved these changes
Avaliação realizada. Considero APROVADO.

2021-11-23 15:12 UTC, marcos1079 requested changes
Talvez não tenha deixado claro, mas a intenção é que a barra do scroll ficasse no canto da tela e não ao meio.

2021-11-25 01:29 UTC, marcos1079 approved these changes

2021-11-25 01:29 UTC, thaisclxt commented
Conforme as correções feitas, considero o pull request, como um todo, APROVADO.

2021-11-25 01:30 UTC, merged