Develop
disciplinas-prof-Edeilson-UFT/proj-sist-2021-2 pull request #21
Opened 2021-11-22 01:44 UTC by FilipeMSouza

Pedido de revisão e merge do requisito R15.

- [Card no Trello](https://trello.com/c/aCITYvQj/6-r15-lojista-cadastrar-produto)
- Grupo revisor: Grupo 2
- [21/11] - Pull Request criada para revisão

-----

### Como acessar
Para acessar a página de administração de dados sigilosos, clique em **Ifood Empresas** no _footer_ da _home screen_, em seguida em um card com um símbolo **+** na página home do restaurante.

### Para ter certeza
Ao acessar o banco pode-se conferir tanto no Storage na pasta **product_image** quanto no **firestore Database**

2021-11-25 04:44 UTC, itzmyhub commented on lib/app/global/repositories/products/product_repository.dart
> +      await FirebaseFirestore.instance.collection('products').add({
Acredito que seja melhor efetuar a checagem de "productSetImage" antes de adicionar o documento ao banco, caso contrário o documento vai poder ser criado mesmo sem a imagem definida. Fiz um teste colocando um .txt

2021-11-25 16:50 UTC, FilipeMSouza commented on lib/app/global/repositories/products/product_repository.dart
> +      await FirebaseFirestore.instance.collection('products').add({
resolvido

2021-11-26 00:36 UTC, itzmyhub commented on lib/app/modules/restaurant_home/components/add_product_components/product_image.dart
> +import 'package:flutter/material.dart';
É interessante colocar uma resposta para o usuário que a imagem foi recebida/colocada. No modelo atual o usuário não tem essa resposta.

2021-11-26 01:01 UTC, itzmyhub commented on lib/app/modules/restaurant_home/pages/product/add_product_card.dart
>  import 'package:flutter/material.dart';
É interessante colocar uma resposta para o usuário que a imagem foi recebida/colocada. No modelo atual o usuário não tem essa resposta. Outra coisa, tentei colocar um txt no espaço e não me acusou erro no front, apesar do arquivo não ter ido para o firestorage. A idéia é essa: repassar uma resposta de erro ou que a imagem está para ser carregada para o usuário. Além disso, sugiro retirar o botão "img" e deixar apenas o seguinte, no próprio contexto de cadastro e abaixo de todos os demais campos de texto:
![image](https://user-images.githubusercontent.com/54652013/143511832-16681ab6-7b46-477c-a1f8-ce089b15acd8.png)
![image](https://user-images.githubusercontent.com/54652013/143511652-87ab227e-6581-49b9-932b-7aec0120aa1e.png)
Por fim, tentem alinhar o botão de save com o fim das caixas de textos:
![image](https://user-images.githubusercontent.com/54652013/143511768-a70bbc77-eebf-4954-8bd9-d8d04f6d8af9.png)

2021-11-26 01:05 UTC, itzmyhub requested changes
Desculpem pela demora do review!

Os comentários das modificações necessárias estão nos respectivos arquivos.

2021-11-26 01:42 UTC, FilipeMSouza commented on lib/app/modules/restaurant_home/pages/product/add_product_card.dart
>  import 'package:flutter/material.dart';
Tá feito meu patrão

2021-11-29 21:49 UTC, djesusguimaraes commented
## Usabilidade

1. Não há mensagem de validação para os dois campos finais:
     ![image](https://user-images.githubusercontent.com/66970708/143936452-e77b73a3-fdcc-4bc4-ad00-62a284e97d89.png)
2. Ao adicionar uma imagem o popup se fecha;

3. Os dados seguem salvos mesmo após fechar o popup;

4. Pixel Overflow ao diminuir heigth:
  ![image](https://user-images.githubusercontent.com/66970708/143944647-1f0fe169-124d-4c18-8a2f-030af3480c94.png)
 
5. Os ícones desalinhados estão afetando o layout:
   ![image](https://user-images.githubusercontent.com/66970708/143937397-65795c81-3048-4a92-bab3-d400e46dd52e.png)

   **OBS**: 

    * A imagem acima é apenas um esboço de como deve ficar a correção dos alinhamentos.

    * Uma forma simples e rápida de organizar as validações e o layout seria ultilizar widgets já presentes no projeto, como o `CustomTextField` e o `CustomSubmit`.

2021-11-29 21:53 UTC, djesusguimaraes requested changes
## Conclusão

Dadas as observações sobre usabilidade e qualidade de código. Considero o [card](https://trello.com/c/aCITYvQj/6-r15-lojista-cadastrar-produto) REPROVADO na 2ª Revisão.

2021-11-29 21:53 UTC, djesusguimaraes commented on lib/app/modules/restaurant_home/pages/product/add_product_card.dart
> +                          store.cadastrarProdutoTeste(produto);
É interessante que a nomenclatura das funções seja revista já que não se trata mais de um evento de teste.

2021-11-29 21:53 UTC, djesusguimaraes commented on lib/app/modules/restaurant_home/pages/product/add_product_card.dart
> +import 'package:pscomidas/app/modules/home/schemas.dart';
Import não ultilizado.

2021-12-01 06:59 UTC, itzmyhub commented on lib/app/modules/restaurant_home/pages/product/add_product_card.dart
> +                          store.cadastroProduto();
O botão de salvar precisa executar a ação de cadastro de produto sob a condição de todos os campos estarem validados. Por mais que a validação apareça na tela - "esse campo não pode ficar vazio" - a ação é executada independentemente e o produto adicionado ao firebase. Quando o salvar for executado com sucesso (lançar mensagem de confirmação - pode ser um flushbar como o de quando a imagem é inválida), os valores dos text editing tem que ser limpos (caso contrário, os valores vão ficar salvo ao abrir pra adicionar outro produto). Acredito que isso seja tudo.

2021-12-04 21:19 UTC, djesusguimaraes commented
## Usabilidade

1. Clicar em "Salvar" com o formulário vazio:
   * O formulário se fecha;
   * É apresentada mensagem de sucesso no cadastro;
2. Validações não são disparadas corretamente
   * As validações só iniciam ao errar no terceiro campo
   * Mesmo com as mensagens de erro na tela o formulário é fechado ao clicar em "Salvar"

2021-12-05 23:38 UTC, itzmyhub commented
1. Clicar em salvar, independente de todos os campos estarem preenchidos lança a mensagem de erro no cadastro.
-Provavelmente a verificação de nulidade não está sendo satisfeita, acredito que estes checks podem ser substituídos por um ".text.isNotEmpty" - não tenho certeza por ser um map;
2. Os dados continuam sendo adicionados ao banco se apenas a caixa de texto de "preço" estiver preenchida, como segue nas imagens abaixo.
-Adicionando documento com apenas o preço e uma imagem inserida:
![image](https://user-images.githubusercontent.com/54652013/144768589-d72bde8b-0070-4511-b73a-12a312b8ef66.png)

-No firebase:
![image](https://user-images.githubusercontent.com/54652013/144768636-8862855d-e1e0-4ec3-9d76-1f270e623ca5.png)

-Possível solução: remover o método store.cadastroProduto() da execução de "salvar";
![image](https://user-images.githubusercontent.com/54652013/144768401-e2ee02b2-caf7-4abe-ba4d-d2e3616b536b.png)

3. O formulário nunca é fechado, pois acredito que a condicional if nunca está sendo satisfeita, precisamos que as correções sejam feitas para verificar este case.

2021-12-05 23:42 UTC, FilipeMSouza commented
> 1. Clicar em salvar, independente de todos os campos estarem preenchidos lança a mensagem de erro no cadastro.
>    -Provavelmente a verificação de nulidade não está sendo satisfeita, acredito que estes checks podem ser substituídos por um ".text.isNotEmpty" - não tenho certeza por ser um map;
> 2. Os dados continuam sendo adicionados ao banco se apenas a caixa de texto de "preço" estiver preenchida, como segue nas imagens abaixo.
>    -Adicionando documento com apenas o preço e uma imagem inserida:
>    ![image](https://user-images.githubusercontent.com/54652013/144768589-d72bde8b-0070-4511-b73a-12a312b8ef66.png)
> 
> -No firebase: ![image](https://user-images.githubusercontent.com/54652013/144768636-8862855d-e1e0-4ec3-9d76-1f270e623ca5.png)
> 
> -Possível solução: remover o método store.cadastroProduto() da execução de "salvar"; ![image](https://user-images.githubusercontent.com/54652013/144768401-e2ee02b2-caf7-4abe-ba4d-d2e3616b536b.png)
> 
> 3. O formulário nunca é fechado, pois acredito que a condicional if nunca está sendo satisfeita, precisamos que as correções sejam feitas para verificar este case.

----- 

- Resolvido eu acabei percebendo isso dps de eu ter enviado a primeira vez e logo em sequencia eu corrigi e enviei, mals ae meu querido

2021-12-06 01:43 UTC, djesusguimaraes commented
## Conclusão

Acabo de conferir o produto e dado o fato que as observações foram atendidas, e as respostas estão sendo apresentadas ao cliente, considero o card APROVADO.

2021-12-06 01:43 UTC, merged