R14 - [Cliente] Cadastro de Cartões
disciplinas-prof-Edeilson-UFT/proj-sist-2021-2 pull request #26
Opened 2021-12-06 13:09 UTC by FilipeMSouza

[card](https://trello.com/c/9m0lEu94/13-r14-cliente-gerenciar-cart%C3%B5es-de-cr%C3%A9dito)
- Cadastro de cartões
- Grupoi revisor Grupo 2
- entrega para revisao [6/12/2021]

2021-12-11 03:09 UTC, djesusguimaraes requested changes
## Detalhes

Como houve impedimento nos testes causado por dados estáticos considero REPROVADO.

2021-12-11 03:09 UTC, djesusguimaraes commented on lib/app/global/repositories/paymentcard/payment_card.dart
> +      }).then((value) {
Não falta o `CPF` do dono do cartão?

2021-12-11 03:09 UTC, djesusguimaraes commented on lib/app/modules/payments/components/add_card/TextField/text_field_card.dart
> +import 'package:flutter/material.dart';
**Sobre os arquivos anteriores**
* As imagens e assets não deveriam estar na pasta global do projeto?
  `proj-sist-2021-2/assets`

2021-12-11 03:09 UTC, djesusguimaraes commented on lib/app/modules/payments/components/add_card/add_body.dart
> +          height: 50,
**Observers desnecessários**
* Dada a estrutura de widgets o `Material` na linha `29` não necessita ser retornado por um Observer, já que o foco final é o `IconButton`, que já é retornado por um Observer.

2021-12-11 03:09 UTC, djesusguimaraes commented on lib/app/modules/payments/components/add_card/form_card.dart
> +                            hintText: 'Numero do cartão',
**Falta de limite e máscara**

O campo aceita mais que os caracteres necessários.
Além de não organizar a entrada dos números.

Esse tipo de comportamento pode dificultar a experiência do usuário final.

2021-12-11 03:09 UTC, djesusguimaraes commented on lib/app/modules/payments/components/cards_payments/list_card.dart
> +          itemCount: 1, // numero de cartões cadastrados
**Dados Estáticos**

Os dados da listagem de cartão estão estáticos, logo se explica a falta de atualização ao cadastrar um novo cartão.

2021-12-11 03:09 UTC, djesusguimaraes commented on lib/app/modules/payments/components/add_card/form_card.dart
> +                            hintText: 'Numero do cartão',
Todos os campos aceitam letras (String) como entrada, mesmo para valores declaradamente numéricos.

2021-12-11 03:11 UTC, djesusguimaraes commented
## Observação

**Lembrem-se de atualizar a branch para resolver os conflitos**

2021-12-11 03:43 UTC, vhgomes commented on lib/app/global/repositories/paymentcard/payment_card.dart
> +      }).then((value) {
O CPF é atrelado a conta do usuário logado, acredito que não seja necessário colocar no registro do cartão.

2021-12-11 03:48 UTC, vhgomes commented on lib/app/global/repositories/paymentcard/payment_card.dart
> +      }).then((value) {
![image](https://user-images.githubusercontent.com/60026761/145662652-1ffefd9b-59b5-4920-996e-167646156c22.png)

O problema pode ser o seguinte, caso ter sido cadastrado por outros meio de terceiros (Google, Facebook) pois ai não terá o campo de CPF, porém caso for registrado pelos campos normalmente, o CPF já vai estar cadastrado na conta.

2021-12-11 15:08 UTC, djesusguimaraes commented on lib/app/global/repositories/paymentcard/payment_card.dart
> +      }).then((value) {
Não há garantia que o cartão é do cliente logado. Por isso o cadastro de cartão em todas as plataformas digitais pede o CPF vinculado ao cartão, sem levar em conta a relação com a conta de usuário no site/plataforma.

Ex, próprio Ifood:
![image](https://user-images.githubusercontent.com/66970708/145681443-87220e0d-9c3c-4c28-9651-fafdab079b2c.png)

2021-12-11 16:33 UTC, vhgomes commented on lib/app/global/repositories/paymentcard/payment_card.dart
> +      }).then((value) {
Saquei saquei, mas como eu sou rápido isso ai já foi arrumado, inseri o campo aqui. Valeu.

2021-12-13 05:32 UTC, djesusguimaraes approved these changes

2021-12-13 05:35 UTC, djesusguimaraes commented
## Conclusão

Dada a semântica do requisito, que trata apenas da inserção de cartões, considero aceitável a falta das funções de deleção e atualização.

2021-12-13 05:36 UTC, merged